---
- name: Install, start, enable, and verify Nginx
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Install node rpm files
      ansible.builtin.shell: curl -fsSL https://rpm.nodesource.com/setup_22.x | bash -
    
    - name: Install Nginx & nodejs
      ansible.builtin.dnf:
        name: 
         - '@nginx:1.26'
         - nodejs
        state: present

    - name: Update the Nginx configuration file
      ansible.builtin.copy:
        src: nginx.conf
        dest: /etc/nginx/conf.d/nginx.conf
        # owner: root
        # group: root
        # mode: '0644'
    - name: Start and enable Nginx
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: true
        daemon_reload: true

    - name: Download and extract the file
      ansible.builtin.unarchive:
        src: https://raw.githubusercontent.com/raghudevopsb88/wealth-project/main/artifacts/frontend.tar.gz
        dest: /tmp/
        remote_src: yes

    - name: Build the frontend application
      ansible.builtin.shell: |
        cd /tmp
        npm ci
        npm run build
    
    - name: Remove existing HTML files
      ansible.builtin.file:
        path: /usr/share/nginx/html/*.html
        state: absent

    - name: Copy the built frontend files to Nginx's HTML directory
      ansible.builtin.copy:
        src: /tmp/dist/
        dest: /usr/share/nginx/html/
        remote_src: yes

    - name: Check whether Nginx is active
      ansible.builtin.systemd_service:
        name: nginx
        enabled: true
        state: restarted