---
- name: Install, start, enable, and verify Nginx
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Install Nginx when it is not installed
      ansible.builtin.dnf:
        name: '@nginx:1.26'
        state: present

    - name: Copy the copy file to the Nginx configuration directory
      ansible.builtin.copy:
        src: ./nginx.conf
        dest: /etc/nginx/conf.d/frontend.conf
        owner: root
        group: root
        mode: '0644'