- name: To install Nginx




  tasks:
    - name: Install Nginx package
      ansible.builtin.dnf:
        name: nginx
        state: latest

  # tasks:
  #   - name: Install Nginx package
  #     apt:
  #       name: nginx
  #       state: present
  #     notify:
  #       - Start Nginx

  # handlers:
  #   - name: Start Nginx
  #     service:
  #       name: nginx
  #       state: started