- name: To install Nginx
  ansible.builtin.dnf:
    name: nginx
    state: latest

  # tasks:
  #   - name: Install Nginx package
  #     apt:
  #       name: nginx
  #       state: present
  #     notify:
  #       - Start Nginx

  # handlers:
  #   - name: Start Nginx
  #     service:
  #       name: nginx
  #       state: started